### ISSUE TITLE
read from SAFE files with and without measurements: 

### ISSUE THREAD

**Issue by hfattahi** [opera-adt/s1-reader#22]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

Without this feature we won't be able to read unzipped files. Also we won't be able to read only downloaded metadata files. 

### Describe the feature request

s1reader currently only reads the ".zip" files. It should be able to read both zipfile and ".SAFE" files. For the latter we should be able to read a .SAFE file which may or may not contain any actual measurements. For example if we download only the annotation files, which is possible [using this](https://github.com/avalentino/asfsmd), we want to be able to read the downloaded metadata.

**Comment by LiangJYu** [comment]
`s1_reader` [reads](https://github.com/opera-adt/s1-reader/blob/b8de577fe8c807f3375db1be7775032327cb6295/src/s1reader/s1_reader.py#L250) an XML from a provided path. The zip reader is a [wrapper](https://github.com/opera-adt/s1-reader/blob/b8de577fe8c807f3375db1be7775032327cb6295/src/s1reader/s1_reader.py#L451) around the XML reader.

**Comment by hfattahi** [comment]
@LiangJYu yes I understand that. However that is not the interface we want at the high-level. Forexample the burst_from_xml requires the path to the xml and tiff files. User of the reader should not do that. burst_from_xml does not need to change. We can either add another function similar to burst_from_zip with the following arguments:

burst_from_safe(safe_path: str, orbit_path: str, swath_num: int, pol: str = 'vv')

or generalize burst_from_zip to ```get_burst(file_path: str, orbit_path: str, swath_num: int, pol: str = 'vv')``` where ```file_path``` can be a zip file or a unzipped version of it, i.e., ".SAFE" file. 

For the second need where we only have the annotation file, what we download is same as the zip file, with two differences. One it may not be zipped and it does not have measurements (i.e., tiff file).
