### ISSUE TITLE
[Bug]: CircleCI unable to install dependencies

### ISSUE THREAD

**Issue by LiangJYu** [opera-adt/s1-reader#65]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

[CI fail](https://app.circleci.com/pipelines/github/opera-adt/s1-reader/64/workflows/b18feb79-f725-4e4d-b198-6e7201cd0dbb/jobs/61) occurs for this [PR](https://github.com/opera-adt/s1-reader/pull/64).

I'm guessing links in specfile are dead? Packages ending in `.conda` are no longer present at https://repo.anaconda.com/pkgs/main/linux-64/.

### What did you expect?

I expected dependency installation to not to fail.

### Reproducible steps

```bash
Push something to the PR.
```

### Environment

```bash
CircleCI
```

**Comment by rtburns-jpl** [comment]
I'll try to refresh the specfile to fix this. Do you think we should update the isce3 version as well? We're currently pinning to 0.6 here, latest is 0.8.

**Comment by LiangJYu** [comment]
Going to 0.8 is a good idea.

**Comment by rtburns-jpl** [comment]
Hmm, I'm bumping the specfile but the zlib url isn't changing. Is it possible that CI failure was transient? Tbh I wouldn't expect those download urls to expire, since they're supposed to be used this way.

**Comment by rtburns-jpl** [comment]
Still not sure why this started happening but the issue appears to be only with the defaults channel. https://github.com/opera-adt/s1-reader/pull/66 switches all packages to use the conda-forge channel, which I think is preferable anyway.
